title: Un format de rétrospective sérieux mais un peu plus léger que d'habitude (et
  qui n'a pas encore de nom)
speaker_name: Silvan Cabot
speaker:
  parts:
  - start: 0:00
    stop: 09:51
sound:
  extra_offset: 0.0
slides: {}
