conference:
  jingle: "template/ht/jingle.mp4"
  logo: "template/ht/ht_logo.webp"
  background_image: "template/ht/HT background image.jpeg"

title: "L'art de la négociation, c'est l'affaire de tous."
speaker_name: Victor Vuarnet

speaker:
  parts:
    - start: "0:00"
      stop: "09:51"


sound:
  extra_offset: 0.0

slides:

