title: "talk-test"
speaker_name: "Prenom Nom"

speaker:
  parts:
    - start: "0:00"
      stop: "09:51"


sound:
  file_name: "template/alpescraft/talk-test/speaker.mkv"
  extra_offset: 0.0

slides:
  file_name: "template/alpescraft/talk-test/speaker.mkv"
