title: Contrôle de la température de sites de calcul grâce à l'injection de tâches
  utiles et non invasives
speaker_name: Kouds Halitim
speaker:
  parts:
  - start: 0:00
    stop: 09:51
sound:
  extra_offset: 0.0
slides: {}
